# Generated by Django 2.0.8 on 2020-03-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0002_auto_20200314_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='Image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='ele/images'),
        ),
    ]
