# Generated by Django 2.0.8 on 2020-03-14 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0003_auto_20200314_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
