# Generated by Django 2.0.8 on 2020-03-19 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0006_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
