# Generated by Django 2.0.8 on 2020-04-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0008_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
