# Generated by Django 2.0.8 on 2020-04-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0009_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Placed', 'Placed'), ('Acknowledged', 'Acknowledged'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Dispatched', 'Dispatched')], default='Waiting', max_length=50),
        ),
    ]
